[2024-03-29T11:31:26.552+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-29T09:27:01.658200+00:00 [queued]>
[2024-03-29T11:31:26.583+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-29T09:27:01.658200+00:00 [queued]>
[2024-03-29T11:31:26.583+0200] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2024-03-29T11:31:26.603+0200] {taskinstance.py:2214} INFO - Executing <Task(ExternalTaskSensor): process_result.sensor_triggered_dag> on 2024-03-29 09:27:01.658200+00:00
[2024-03-29T11:31:26.610+0200] {standard_task_runner.py:60} INFO - Started process 35155 to run task
[2024-03-29T11:31:26.621+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'process_result.sensor_triggered_dag', 'manual__2024-03-29T09:27:01.658200+00:00', '--job-id', '1225', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmphh0raubm']
[2024-03-29T11:31:26.625+0200] {standard_task_runner.py:88} INFO - Job 1225: Subtask process_result.sensor_triggered_dag
[2024-03-29T11:31:26.738+0200] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-29T09:27:01.658200+00:00 [running]> on host C9843
[2024-03-29T11:31:26.904+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='process_result.sensor_triggered_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T09:27:01.658200+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T09:27:01.658200+00:00'
[2024-03-29T11:31:26.907+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-29T09:22:01.658200+00:00 ... 
[2024-03-29T11:31:36.754+0200] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-03-29T11:31:36.770+0200] {process_utils.py:131} INFO - Sending 15 to group 35155. PIDs of all processes in the group: [35155]
[2024-03-29T11:31:36.771+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 35155
[2024-03-29T11:31:36.771+0200] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-29T11:31:36.825+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=35155, status='terminated', exitcode=0, started='11:31:26') (35155) terminated with exit code 0
