[2024-03-12T10:10:22.657+0200] {processor.py:161} INFO - Started process (PID=3277) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:10:22.658+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:10:22.659+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:10:22.659+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:10:22.697+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:10:22.838+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:10:22.827+0200] {dagbag.py:649} ERROR - Failed to write serialized DAG: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1328, in serialize_dag
    serialized_dag["dag_dependencies"] = [x.__dict__ for x in sorted(dag_deps)]
  File "<string>", line 4, in __lt__
TypeError: '<' not supported between instances of 'str' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 166, in write_dag
    new_serialized_dag = cls(dag, processor_subdir)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 113, in __init__
    dag_data = SerializedDAG.to_dict(dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1429, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1344, in serialize_dag
    raise SerializationError(f"Failed to serialize DAG {dag.dag_id!r}: {e}")
airflow.exceptions.SerializationError: Failed to serialize DAG 'trigger_dag': '<' not supported between instances of 'str' and 'NoneType'
[2024-03-12T10:10:22.838+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:10:22.838+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T10:10:22.849+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:10:22.849+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T10:10:22.870+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.214 seconds
[2024-03-12T10:12:54.465+0200] {processor.py:161} INFO - Started process (PID=3475) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:12:54.467+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:12:54.468+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:12:54.468+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:12:54.503+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:12:54.648+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:12:54.637+0200] {dagbag.py:649} ERROR - Failed to write serialized DAG: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1328, in serialize_dag
    serialized_dag["dag_dependencies"] = [x.__dict__ for x in sorted(dag_deps)]
  File "<string>", line 4, in __lt__
TypeError: '<' not supported between instances of 'str' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 166, in write_dag
    new_serialized_dag = cls(dag, processor_subdir)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 113, in __init__
    dag_data = SerializedDAG.to_dict(dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1429, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1344, in serialize_dag
    raise SerializationError(f"Failed to serialize DAG {dag.dag_id!r}: {e}")
airflow.exceptions.SerializationError: Failed to serialize DAG 'trigger_dag': '<' not supported between instances of 'str' and 'NoneType'
[2024-03-12T10:12:54.648+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:12:54.648+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T10:12:54.659+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:12:54.658+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T10:12:54.680+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.216 seconds
[2024-03-12T10:14:46.178+0200] {processor.py:161} INFO - Started process (PID=3613) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:14:46.179+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:14:46.179+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:14:46.179+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:14:46.207+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:14:46.335+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:14:46.333+0200] {dagbag.py:649} ERROR - Failed to write serialized DAG: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1328, in serialize_dag
    serialized_dag["dag_dependencies"] = [x.__dict__ for x in sorted(dag_deps)]
  File "<string>", line 4, in __lt__
TypeError: '<' not supported between instances of 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 166, in write_dag
    new_serialized_dag = cls(dag, processor_subdir)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 113, in __init__
    dag_data = SerializedDAG.to_dict(dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1429, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1344, in serialize_dag
    raise SerializationError(f"Failed to serialize DAG {dag.dag_id!r}: {e}")
airflow.exceptions.SerializationError: Failed to serialize DAG 'trigger_dag': '<' not supported between instances of 'NoneType' and 'str'
[2024-03-12T10:14:46.336+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:14:46.336+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T10:14:46.346+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:14:46.346+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T10:14:46.366+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.189 seconds
[2024-03-12T10:16:31.073+0200] {processor.py:161} INFO - Started process (PID=3726) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:16:31.075+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:16:31.076+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:16:31.076+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:16:31.112+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:16:31.257+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:16:31.247+0200] {dagbag.py:649} ERROR - Failed to write serialized DAG: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1328, in serialize_dag
    serialized_dag["dag_dependencies"] = [x.__dict__ for x in sorted(dag_deps)]
  File "<string>", line 4, in __lt__
TypeError: '<' not supported between instances of 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 166, in write_dag
    new_serialized_dag = cls(dag, processor_subdir)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 113, in __init__
    dag_data = SerializedDAG.to_dict(dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1429, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1344, in serialize_dag
    raise SerializationError(f"Failed to serialize DAG {dag.dag_id!r}: {e}")
airflow.exceptions.SerializationError: Failed to serialize DAG 'trigger_dag': '<' not supported between instances of 'NoneType' and 'str'
[2024-03-12T10:16:31.258+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:16:31.258+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T10:16:31.268+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:16:31.268+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T10:16:31.288+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.216 seconds
[2024-03-12T10:27:52.696+0200] {processor.py:161} INFO - Started process (PID=4104) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:27:52.698+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:27:52.699+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:27:52.699+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:27:52.713+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:27:52.713+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from dags.subdag_task import subdag_process
ModuleNotFoundError: No module named 'dags'
[2024-03-12T10:27:52.714+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:27:52.787+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.092 seconds
[2024-03-12T10:30:20.488+0200] {processor.py:161} INFO - Started process (PID=4277) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:30:20.489+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:30:20.489+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:30:20.489+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:30:20.506+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:30:20.505+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from dags.subdag_task import subdag_process
ModuleNotFoundError: No module named 'dags'
[2024-03-12T10:30:20.506+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:30:20.583+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.096 seconds
[2024-03-12T10:32:09.001+0200] {processor.py:161} INFO - Started process (PID=4407) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:32:09.002+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:32:09.003+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:32:09.003+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:32:09.018+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:32:09.017+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from dags.subdag_task import subdag_process
ModuleNotFoundError: No module named 'dags'
[2024-03-12T10:32:09.018+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:32:09.093+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.093 seconds
[2024-03-12T10:34:02.305+0200] {processor.py:161} INFO - Started process (PID=4573) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:34:02.307+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:34:02.307+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:34:02.307+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:34:02.323+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:34:02.322+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from dags.subdag_task import subdag_process
ModuleNotFoundError: No module named 'dags'
[2024-03-12T10:34:02.323+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:34:02.436+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.132 seconds
[2024-03-12T10:35:57.432+0200] {processor.py:161} INFO - Started process (PID=4701) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:35:57.433+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:35:57.434+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:35:57.434+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:35:57.450+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:35:57.449+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from dags.subdag_task import subdag_process
ModuleNotFoundError: No module named 'dags'
[2024-03-12T10:35:57.450+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:35:57.531+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.100 seconds
[2024-03-12T10:37:46.786+0200] {processor.py:161} INFO - Started process (PID=4842) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:37:46.787+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:37:46.788+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:37:46.787+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:37:46.803+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:37:46.803+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from dags.subdag_task import subdag_process
ModuleNotFoundError: No module named 'dags'
[2024-03-12T10:37:46.803+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:37:46.876+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.091 seconds
[2024-03-12T10:39:38.784+0200] {processor.py:161} INFO - Started process (PID=4980) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:39:38.785+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:39:38.786+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:39:38.786+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:39:38.802+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:39:38.802+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from dags.subdag_task import subdag_process
ModuleNotFoundError: No module named 'dags'
[2024-03-12T10:39:38.803+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:39:38.890+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.107 seconds
[2024-03-12T10:41:23.150+0200] {processor.py:161} INFO - Started process (PID=5089) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:41:23.152+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:41:23.153+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:41:23.153+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:41:23.185+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:41:23.184+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from dags.subdag_task import subdag_process
ModuleNotFoundError: No module named 'dags'
[2024-03-12T10:41:23.185+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:41:23.296+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.147 seconds
[2024-03-12T10:43:08.466+0200] {processor.py:161} INFO - Started process (PID=5227) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:43:08.467+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:43:08.467+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:43:08.467+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:43:08.483+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:43:08.483+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from dags.subdag_task import subdag_process
ModuleNotFoundError: No module named 'dags'
[2024-03-12T10:43:08.484+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:43:08.559+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.094 seconds
[2024-03-12T10:45:02.455+0200] {processor.py:161} INFO - Started process (PID=5346) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:45:02.456+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:45:02.456+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:45:02.456+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:45:02.597+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag.process_task', 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:45:02.706+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:45:02.706+0200] {dag.py:3047} INFO - Sync 2 DAGs
[2024-03-12T10:45:02.715+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:45:02.715+0200] {dag.py:3069} INFO - Creating ORM DAG for trigger_dag.process_task
[2024-03-12T10:45:02.715+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:45:02.715+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T10:45:02.718+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:45:02.717+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag.process_task to None, run_after=None
[2024-03-12T10:45:02.726+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:45:02.726+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T10:45:02.728+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:45:02.728+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag.process_task to None, run_after=None
[2024-03-12T10:45:02.741+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.288 seconds
[2024-03-12T10:46:55.512+0200] {processor.py:161} INFO - Started process (PID=5487) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:46:55.513+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:46:55.513+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:46:55.513+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:46:55.551+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:46:55.548+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 39, in <module>
    process_task = SubDagOperator(
  File "/usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 437, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/subdag.py", line 97, in __init__
    self._validate_pool(session)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/subdag.py", line 119, in _validate_pool
    conflicts = [t for t in self.subdag.tasks if t.pool == self.pool]
AttributeError: 'TaskGroup' object has no attribute 'tasks'
[2024-03-12T10:46:55.551+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:46:55.673+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.162 seconds
[2024-03-12T10:48:41.477+0200] {processor.py:161} INFO - Started process (PID=5619) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:48:41.478+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:48:41.479+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:48:41.479+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:48:41.517+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:48:41.514+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 41, in <module>
    process_task = subdag_process('trigger_dag', 'process_task_group', None)
  File "/Users/abatcoveanu/airflow/dags/subdag_task.py", line 42, in subdag_process
    process_tasks = TaskGroup(group_id='process_tasks', dag=dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 129, in __init__
    raise RuntimeError(
RuntimeError: ('Cannot mix TaskGroups from different DAGs: %s and %s', <DAG: trigger_dag.process_task_group>, <DAG: trigger_dag>)
[2024-03-12T10:48:41.517+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:48:41.637+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.161 seconds
[2024-03-12T10:50:37.206+0200] {processor.py:161} INFO - Started process (PID=5740) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:50:37.207+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:50:37.207+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:50:37.207+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:50:37.243+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:50:37.241+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 45, in <module>
    process_task>> wait_run_file >> trigger_dag
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-03-12T10:50:37.244+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:50:37.364+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.159 seconds
[2024-03-12T10:52:29.695+0200] {processor.py:161} INFO - Started process (PID=5855) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:52:29.695+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:52:29.696+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:52:29.696+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:52:29.725+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:52:29.725+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 45, in <module>
    process_task>> wait_run_file >> trigger_dag
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 109, in __rrshift__
    self.__lshift__(other)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 99, in __lshift__
    self.set_upstream(other)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 270, in set_upstream
    self._set_relatives(task_or_task_list, upstream=True, edge_modifier=edge_modifier)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'DAG' object has no attribute 'update_relative'
[2024-03-12T10:52:29.726+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:52:29.833+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.140 seconds
[2024-03-12T10:54:13.872+0200] {processor.py:161} INFO - Started process (PID=5976) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:54:13.873+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:54:13.873+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:54:13.873+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:54:13.907+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:54:13.906+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 42, in <module>
    process_task_group >> wait_run_file >> trigger_dag
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 335, in _set_relatives
    task.set_downstream(task_or_task_list)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 228, in _set_relatives
    raise AirflowException(f"Tried to set relationships between tasks in more than one DAG: {dags}")
airflow.exceptions.AirflowException: Tried to set relationships between tasks in more than one DAG: {<DAG: trigger_dag.process_task_group>, <DAG: trigger_dag>}
[2024-03-12T10:54:13.907+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:54:14.019+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.149 seconds
[2024-03-12T10:56:00.866+0200] {processor.py:161} INFO - Started process (PID=6104) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:56:00.867+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:56:00.867+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:56:00.867+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:56:00.902+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:56:00.901+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 42, in <module>
    process_task_group >> wait_run_file >> trigger_dag
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 335, in _set_relatives
    task.set_downstream(task_or_task_list)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 228, in _set_relatives
    raise AirflowException(f"Tried to set relationships between tasks in more than one DAG: {dags}")
airflow.exceptions.AirflowException: Tried to set relationships between tasks in more than one DAG: {<DAG: trigger_dag.process_task_group>, <DAG: trigger_dag>}
[2024-03-12T10:56:00.902+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:56:01.023+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.158 seconds
[2024-03-12T10:57:56.638+0200] {processor.py:161} INFO - Started process (PID=6262) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:57:56.638+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:57:56.639+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:57:56.639+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:57:56.669+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:57:56.669+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 42, in <module>
    wait_run_file >> process_task_group
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 228, in _set_relatives
    raise AirflowException(f"Tried to set relationships between tasks in more than one DAG: {dags}")
airflow.exceptions.AirflowException: Tried to set relationships between tasks in more than one DAG: {<DAG: trigger_dag>, <DAG: trigger_dag.process_task_group>}
[2024-03-12T10:57:56.670+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:57:56.776+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.140 seconds
[2024-03-12T10:59:45.897+0200] {processor.py:161} INFO - Started process (PID=6388) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:59:45.898+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T10:59:45.899+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:59:45.899+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:59:45.929+0200] {logging_mixin.py:188} INFO - [2024-03-12T10:59:45.928+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 42, in <module>
    wait_run_file >> process_task_group >> trigger_dag
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 228, in _set_relatives
    raise AirflowException(f"Tried to set relationships between tasks in more than one DAG: {dags}")
airflow.exceptions.AirflowException: Tried to set relationships between tasks in more than one DAG: {<DAG: trigger_dag>, <DAG: trigger_dag.process_task_group>}
[2024-03-12T10:59:45.929+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T10:59:46.038+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.142 seconds
[2024-03-12T11:01:34.341+0200] {processor.py:161} INFO - Started process (PID=6497) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:01:34.342+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:01:34.343+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:01:34.343+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:01:34.371+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:01:34.370+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 42, in <module>
    wait_run_file >> process_task_group >> trigger_dag
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 228, in _set_relatives
    raise AirflowException(f"Tried to set relationships between tasks in more than one DAG: {dags}")
airflow.exceptions.AirflowException: Tried to set relationships between tasks in more than one DAG: {<DAG: trigger_dag.process_task_group>, <DAG: trigger_dag>}
[2024-03-12T11:01:34.371+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:01:34.484+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.144 seconds
[2024-03-12T11:03:21.414+0200] {processor.py:161} INFO - Started process (PID=6625) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:03:21.415+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:03:21.415+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:03:21.415+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:03:21.442+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:03:21.442+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 43, in <module>
    trigger_dag >> process_task_group
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 228, in _set_relatives
    raise AirflowException(f"Tried to set relationships between tasks in more than one DAG: {dags}")
airflow.exceptions.AirflowException: Tried to set relationships between tasks in more than one DAG: {<DAG: trigger_dag.process_task_group>, <DAG: trigger_dag>}
[2024-03-12T11:03:21.443+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:03:21.549+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.136 seconds
[2024-03-12T11:05:14.624+0200] {processor.py:161} INFO - Started process (PID=6775) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:05:14.626+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:05:14.626+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:05:14.626+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:05:14.662+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag', 'trigger_dag.process_task_group' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:05:14.950+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:05:14.950+0200] {override.py:1769} INFO - Created Permission View: can read on DAG:trigger_dag.process_task_group
[2024-03-12T11:05:14.956+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:05:14.956+0200] {override.py:1769} INFO - Created Permission View: can edit on DAG:trigger_dag.process_task_group
[2024-03-12T11:05:14.961+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:05:14.961+0200] {override.py:1769} INFO - Created Permission View: can delete on DAG:trigger_dag.process_task_group
[2024-03-12T11:05:14.961+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:05:14.961+0200] {dag.py:3047} INFO - Sync 2 DAGs
[2024-03-12T11:05:14.971+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:05:14.971+0200] {dag.py:3069} INFO - Creating ORM DAG for trigger_dag.process_task_group
[2024-03-12T11:05:14.972+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:05:14.972+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:05:14.974+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:05:14.974+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag.process_task_group to None, run_after=None
[2024-03-12T11:05:14.993+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.371 seconds
[2024-03-12T11:07:13.797+0200] {processor.py:161} INFO - Started process (PID=6931) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:07:13.799+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:07:13.799+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:07:13.799+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:07:13.841+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:07:14.133+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:07:14.133+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:07:14.144+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:07:14.143+0200] {dag.py:3069} INFO - Creating ORM DAG for trigger_dag
[2024-03-12T11:07:14.144+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:07:14.144+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:07:14.164+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.369 seconds
[2024-03-12T11:09:20.661+0200] {processor.py:161} INFO - Started process (PID=7081) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:09:20.662+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:09:20.662+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:09:20.662+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:09:20.695+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag.process_task_group', 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:09:20.963+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:09:20.963+0200] {dag.py:3047} INFO - Sync 2 DAGs
[2024-03-12T11:09:20.972+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:09:20.971+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:09:20.973+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:09:20.973+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag.process_task_group to None, run_after=None
[2024-03-12T11:09:20.993+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.333 seconds
[2024-03-12T11:11:13.634+0200] {processor.py:161} INFO - Started process (PID=7195) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:11:13.636+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:11:13.636+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:11:13.636+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:11:13.671+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag', 'trigger_dag.process_task_group' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:11:13.818+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:11:13.818+0200] {dag.py:3047} INFO - Sync 2 DAGs
[2024-03-12T11:11:13.827+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:11:13.827+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:11:13.830+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:11:13.830+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag.process_task_group to None, run_after=None
[2024-03-12T11:11:13.845+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.212 seconds
[2024-03-12T11:13:08.255+0200] {processor.py:161} INFO - Started process (PID=7322) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:13:08.256+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:13:08.257+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:13:08.257+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:13:08.267+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:13:08.267+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from subdag_task import subdag_process
  File "/Users/abatcoveanu/airflow/dags/subdag_task.py", line 34
    with TaskGroup()
                   ^
SyntaxError: invalid syntax
[2024-03-12T11:13:08.267+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:13:08.341+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.086 seconds
[2024-03-12T11:15:04.267+0200] {processor.py:161} INFO - Started process (PID=7444) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:15:04.268+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:15:04.268+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:15:04.268+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:15:04.301+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:15:04.300+0200] {dagbag.py:350} ERROR - Failed to import: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/abatcoveanu/airflow/dags/trigger_dag.py", line 9, in <module>
    from subdag_task import subdag_process
  File "/Users/abatcoveanu/airflow/dags/subdag_task.py", line 34, in <module>
    with TaskGroup('taskSection') as dag:
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/task_group.py", line 123, in __init__
    raise AirflowException("TaskGroup can only be used inside a dag")
airflow.exceptions.AirflowException: TaskGroup can only be used inside a dag
[2024-03-12T11:15:04.301+0200] {processor.py:842} WARNING - No viable dags retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:15:04.417+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.151 seconds
[2024-03-12T11:16:59.334+0200] {processor.py:161} INFO - Started process (PID=7593) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:16:59.336+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:16:59.336+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:16:59.336+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:16:59.371+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:16:59.517+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:16:59.508+0200] {dagbag.py:649} ERROR - Failed to write serialized DAG: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1328, in serialize_dag
    serialized_dag["dag_dependencies"] = [x.__dict__ for x in sorted(dag_deps)]
  File "<string>", line 4, in __lt__
TypeError: '<' not supported between instances of 'str' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 166, in write_dag
    new_serialized_dag = cls(dag, processor_subdir)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 113, in __init__
    dag_data = SerializedDAG.to_dict(dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1429, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1344, in serialize_dag
    raise SerializationError(f"Failed to serialize DAG {dag.dag_id!r}: {e}")
airflow.exceptions.SerializationError: Failed to serialize DAG 'trigger_dag': '<' not supported between instances of 'str' and 'NoneType'
[2024-03-12T11:16:59.518+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:16:59.518+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:16:59.528+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:16:59.528+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:16:59.548+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.215 seconds
[2024-03-12T11:17:33.428+0200] {processor.py:161} INFO - Started process (PID=7692) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:17:33.429+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:17:33.429+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:17:33.429+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:17:33.460+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:17:33.590+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:17:33.583+0200] {dagbag.py:649} ERROR - Failed to write serialized DAG: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1328, in serialize_dag
    serialized_dag["dag_dependencies"] = [x.__dict__ for x in sorted(dag_deps)]
  File "<string>", line 4, in __lt__
TypeError: '<' not supported between instances of 'str' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 166, in write_dag
    new_serialized_dag = cls(dag, processor_subdir)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 113, in __init__
    dag_data = SerializedDAG.to_dict(dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1429, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1344, in serialize_dag
    raise SerializationError(f"Failed to serialize DAG {dag.dag_id!r}: {e}")
airflow.exceptions.SerializationError: Failed to serialize DAG 'trigger_dag': '<' not supported between instances of 'str' and 'NoneType'
[2024-03-12T11:17:33.591+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:17:33.590+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:17:33.600+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:17:33.600+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:17:33.619+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.193 seconds
[2024-03-12T11:19:47.992+0200] {processor.py:161} INFO - Started process (PID=7857) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:19:47.993+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:19:47.994+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:19:47.993+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:19:48.027+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:19:48.164+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:19:48.161+0200] {dagbag.py:649} ERROR - Failed to write serialized DAG: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1328, in serialize_dag
    serialized_dag["dag_dependencies"] = [x.__dict__ for x in sorted(dag_deps)]
  File "<string>", line 4, in __lt__
TypeError: '<' not supported between instances of 'NoneType' and 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 637, in _serialize_dag_capturing_errors
    dag_was_updated = SerializedDagModel.write_dag(
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 166, in write_dag
    new_serialized_dag = cls(dag, processor_subdir)
  File "<string>", line 4, in __init__
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 482, in _initialize_instance
    manager.dispatch.init_failure(self, args, kwargs)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/state.py", line 479, in _initialize_instance
    return manager.original_init(*mixed[1:], **kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/serialized_dag.py", line 113, in __init__
    dag_data = SerializedDAG.to_dict(dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1429, in to_dict
    json_dict = {"__version": cls.SERIALIZER_VERSION, "dag": cls.serialize_dag(var)}
  File "/usr/local/lib/python3.8/site-packages/airflow/serialization/serialized_objects.py", line 1344, in serialize_dag
    raise SerializationError(f"Failed to serialize DAG {dag.dag_id!r}: {e}")
airflow.exceptions.SerializationError: Failed to serialize DAG 'trigger_dag': '<' not supported between instances of 'NoneType' and 'str'
[2024-03-12T11:19:48.165+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:19:48.164+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:19:48.174+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:19:48.174+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:19:48.196+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.205 seconds
[2024-03-12T11:21:35.568+0200] {processor.py:161} INFO - Started process (PID=7993) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:21:35.568+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:21:35.569+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:21:35.569+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:21:35.599+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:21:35.818+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:21:35.818+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:21:35.826+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:21:35.826+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:21:35.843+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.277 seconds
[2024-03-12T11:23:33.176+0200] {processor.py:161} INFO - Started process (PID=8106) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:23:33.177+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:23:33.177+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:23:33.177+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:23:33.204+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:23:33.326+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:23:33.326+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:23:33.335+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:23:33.335+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:23:33.351+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.177 seconds
[2024-03-12T11:25:26.060+0200] {processor.py:161} INFO - Started process (PID=8238) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:25:26.061+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:25:26.062+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:25:26.062+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:25:26.092+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:25:26.236+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:25:26.235+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:25:26.246+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:25:26.246+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:25:26.264+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.204 seconds
[2024-03-12T11:27:23.327+0200] {processor.py:161} INFO - Started process (PID=8571) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:27:23.329+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:27:23.329+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:27:23.329+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:27:23.364+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:27:23.588+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:27:23.588+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:27:23.597+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:27:23.596+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:27:23.615+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.290 seconds
[2024-03-12T11:29:23.348+0200] {processor.py:161} INFO - Started process (PID=8754) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:29:23.349+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:29:23.350+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:29:23.350+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:29:23.378+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:29:23.503+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:29:23.503+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:29:23.513+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:29:23.513+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:29:23.531+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.184 seconds
[2024-03-12T11:31:15.090+0200] {processor.py:161} INFO - Started process (PID=8889) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:31:15.092+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:31:15.092+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:31:15.092+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:31:15.125+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:31:15.271+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:31:15.271+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:31:15.281+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:31:15.281+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:31:15.315+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.226 seconds
[2024-03-12T11:33:06.098+0200] {processor.py:161} INFO - Started process (PID=9014) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:33:06.100+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:33:06.100+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:33:06.100+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:33:06.139+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:33:06.137+0200] {dagbag.py:447} ERROR - Failed to bag_dag: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 443, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 462, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 470, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: trigger_dag. Faulty task: remove_run_file
[2024-03-12T11:33:06.139+0200] {processor.py:840} INFO - DAG(s) 'dagTaskGroup' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:33:06.405+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:33:06.405+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:33:06.412+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:33:06.412+0200] {dag.py:3834} INFO - Setting next_dagrun for dagTaskGroup to None, run_after=None
[2024-03-12T11:33:06.429+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.333 seconds
[2024-03-12T11:35:06.928+0200] {processor.py:161} INFO - Started process (PID=9155) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:35:06.930+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:35:06.931+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:35:06.930+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:35:06.965+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:35:06.964+0200] {dagbag.py:447} ERROR - Failed to bag_dag: /Users/abatcoveanu/airflow/dags/trigger_dag.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 443, in _process_modules
    self.bag_dag(dag=dag, root_dag=dag)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 462, in bag_dag
    self._bag_dag(dag=dag, root_dag=root_dag, recursive=True)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 470, in _bag_dag
    check_cycle(dag)  # throws if a task cycle is found
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 79, in check_cycle
    child_to_check = _check_adjacent_tasks(current_task_id, task)
  File "/usr/local/lib/python3.8/site-packages/airflow/utils/dag_cycle_tester.py", line 65, in _check_adjacent_tasks
    raise AirflowDagCycleException(msg)
airflow.exceptions.AirflowDagCycleException: Cycle detected in DAG: trigger_dag. Faulty task: remove_run_file
[2024-03-12T11:35:06.967+0200] {processor.py:840} INFO - DAG(s) 'dagTaskGroup' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:35:06.976+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:35:06.976+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:35:07.093+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:35:07.092+0200] {dag.py:3834} INFO - Setting next_dagrun for dagTaskGroup to None, run_after=None
[2024-03-12T11:35:07.114+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.187 seconds
[2024-03-12T11:37:02.215+0200] {processor.py:161} INFO - Started process (PID=9304) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:37:02.217+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:37:02.217+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:37:02.217+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:37:02.234+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:37:02.526+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:37:02.526+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:37:02.534+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:37:02.534+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:37:02.552+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.338 seconds
[2024-03-12T11:38:53.803+0200] {processor.py:161} INFO - Started process (PID=9445) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:38:53.805+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:38:53.807+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:38:53.806+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:38:53.819+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:38:53.904+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:38:53.904+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:38:53.949+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:38:53.949+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:38:53.967+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.165 seconds
[2024-03-12T11:40:27.342+0200] {processor.py:161} INFO - Started process (PID=9554) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:40:27.343+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:40:27.344+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:40:27.343+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:40:27.354+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:40:27.437+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:40:27.437+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:40:27.480+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:40:27.480+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:40:27.498+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.157 seconds
[2024-03-12T11:42:01.252+0200] {processor.py:161} INFO - Started process (PID=9652) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:42:01.253+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:42:01.253+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:42:01.253+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:42:01.264+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:42:01.348+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:42:01.348+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:42:01.395+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:42:01.395+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:42:01.416+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.165 seconds
[2024-03-12T11:43:34.437+0200] {processor.py:161} INFO - Started process (PID=9774) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:43:34.438+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:43:34.438+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:43:34.438+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:43:34.449+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:43:34.535+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:43:34.535+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:43:34.578+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:43:34.578+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:43:34.599+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.163 seconds
[2024-03-12T11:45:09.021+0200] {processor.py:161} INFO - Started process (PID=9878) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:45:09.022+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:45:09.022+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:45:09.022+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:45:09.034+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:45:09.118+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:45:09.118+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:45:09.161+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:45:09.160+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:45:09.180+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.160 seconds
[2024-03-12T11:46:49.024+0200] {processor.py:161} INFO - Started process (PID=9998) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:46:49.025+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T11:46:49.025+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:46:49.025+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:46:49.040+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T11:46:49.126+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:46:49.126+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T11:46:49.171+0200] {logging_mixin.py:188} INFO - [2024-03-12T11:46:49.170+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T11:46:49.187+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.165 seconds
[2024-03-12T12:18:41.747+0200] {processor.py:161} INFO - Started process (PID=10170) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:18:41.752+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T12:18:41.754+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:18:41.754+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:18:41.811+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:18:42.231+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:18:42.231+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T12:18:42.355+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:18:42.354+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T12:18:42.413+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.672 seconds
[2024-03-12T12:23:20.946+0200] {processor.py:161} INFO - Started process (PID=10338) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:23:20.947+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T12:23:20.947+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:23:20.947+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:23:20.958+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:23:21.042+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:23:21.041+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T12:23:21.084+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:23:21.083+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T12:23:21.101+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.157 seconds
[2024-03-12T12:24:55.061+0200] {processor.py:161} INFO - Started process (PID=10439) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:24:55.062+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T12:24:55.062+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:24:55.062+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:24:55.073+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:24:55.156+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:24:55.156+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T12:24:55.198+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:24:55.198+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T12:24:55.216+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.157 seconds
[2024-03-12T12:26:30.625+0200] {processor.py:161} INFO - Started process (PID=10544) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:26:30.626+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T12:26:30.627+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:26:30.626+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:26:30.656+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:26:30.756+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:26:30.756+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T12:26:30.804+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:26:30.804+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T12:26:30.822+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.200 seconds
[2024-03-12T12:28:16.484+0200] {processor.py:161} INFO - Started process (PID=10684) to work on /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:28:16.485+0200] {processor.py:830} INFO - Processing file /Users/abatcoveanu/airflow/dags/trigger_dag.py for tasks to queue
[2024-03-12T12:28:16.485+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:28:16.485+0200] {dagbag.py:540} INFO - Filling up the DagBag from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:28:16.497+0200] {processor.py:840} INFO - DAG(s) 'trigger_dag' retrieved from /Users/abatcoveanu/airflow/dags/trigger_dag.py
[2024-03-12T12:28:16.578+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:28:16.578+0200] {dag.py:3047} INFO - Sync 1 DAGs
[2024-03-12T12:28:16.621+0200] {logging_mixin.py:188} INFO - [2024-03-12T12:28:16.621+0200] {dag.py:3834} INFO - Setting next_dagrun for trigger_dag to None, run_after=None
[2024-03-12T12:28:16.637+0200] {processor.py:183} INFO - Processing /Users/abatcoveanu/airflow/dags/trigger_dag.py took 0.155 seconds
