[2024-03-15T13:05:45.666+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_id_3.check_table_existence manual__2024-03-15T11:05:30.022953+00:00 [queued]>
[2024-03-15T13:05:45.674+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_id_3.check_table_existence manual__2024-03-15T11:05:30.022953+00:00 [queued]>
[2024-03-15T13:05:45.674+0200] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-15T13:05:45.685+0200] {taskinstance.py:2214} INFO - Executing <Task(BranchPythonOperator): check_table_existence> on 2024-03-15 11:05:30.022953+00:00
[2024-03-15T13:05:45.690+0200] {standard_task_runner.py:60} INFO - Started process 48622 to run task
[2024-03-15T13:05:45.696+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'dag_id_3', 'check_table_existence', 'manual__2024-03-15T11:05:30.022953+00:00', '--job-id', '103', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmpoamqss70']
[2024-03-15T13:05:45.698+0200] {standard_task_runner.py:88} INFO - Job 103: Subtask check_table_existence
[2024-03-15T13:05:45.815+0200] {task_command.py:423} INFO - Running <TaskInstance: dag_id_3.check_table_existence manual__2024-03-15T11:05:30.022953+00:00 [running]> on host C9843
[2024-03-15T13:05:45.974+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_id_3' AIRFLOW_CTX_TASK_ID='check_table_existence' AIRFLOW_CTX_EXECUTION_DATE='2024-03-15T11:05:30.022953+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-15T11:05:30.022953+00:00'
[2024-03-15T13:05:45.989+0200] {base.py:83} INFO - Using connection ID 'postgres_default' for task execution.
[2024-03-15T13:05:45.992+0200] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 234, in execute
    return self.do_branch(context, super().execute(context))
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/abatcoveanu/airflow/dags/jobs_dag.py", line 34, in check_table_existence
    table_exists = hook.get_first(sql_query)
  File "/usr/local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 276, in get_first
    return self.run(sql=sql, parameters=parameters, handler=fetch_one_handler)
  File "/usr/local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 397, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 161, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/usr/local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: nodename nor servname provided, or not known

[2024-03-15T13:05:46.016+0200] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=dag_id_3, task_id=check_table_existence, execution_date=20240315T110530, start_date=20240315T110545, end_date=20240315T110546
[2024-03-15T13:05:46.029+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 103 for task check_table_existence (could not translate host name "postgres" to address: nodename nor servname provided, or not known
; 48622)
[2024-03-15T13:05:46.041+0200] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-03-15T13:05:46.076+0200] {logging_mixin.py:188} WARNING - /usr/local/lib/python3.8/site-packages/airflow/models/baseoperator.py:1201 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2024-03-15T13:05:46.115+0200] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
