[2024-04-04T11:26:05.205+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.trigger_dag_task scheduled__2018-11-25T00:00:00+00:00 [queued]>
[2024-04-04T11:26:05.239+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.trigger_dag_task scheduled__2018-11-25T00:00:00+00:00 [queued]>
[2024-04-04T11:26:05.240+0300] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2024-04-04T11:26:05.263+0300] {taskinstance.py:2214} INFO - Executing <Task(TriggerDagRunOperator): trigger_dag_task> on 2018-11-25 00:00:00+00:00
[2024-04-04T11:26:05.268+0300] {standard_task_runner.py:60} INFO - Started process 32624 to run task
[2024-04-04T11:26:05.276+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'trigger_dag_task', 'scheduled__2018-11-25T00:00:00+00:00', '--job-id', '1673', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmpy4yjwhs3']
[2024-04-04T11:26:05.278+0300] {standard_task_runner.py:88} INFO - Job 1673: Subtask trigger_dag_task
[2024-04-04T11:26:05.405+0300] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.trigger_dag_task scheduled__2018-11-25T00:00:00+00:00 [running]> on host C9843
[2024-04-04T11:26:05.606+0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='trigger_dag_task' AIRFLOW_CTX_EXECUTION_DATE='2018-11-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-11-25T00:00:00+00:00'
[2024-04-04T11:26:05.796+0300] {trigger_dagrun.py:210} INFO - Waiting for dag_id_3 on 2024-04-04 08:26:05.609074+00:00 to become allowed state ['success'] ...
[2024-04-04T11:26:15.437+0300] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-04-04T11:26:15.454+0300] {process_utils.py:131} INFO - Sending 15 to group 32624. PIDs of all processes in the group: [32624]
[2024-04-04T11:26:15.455+0300] {process_utils.py:86} INFO - Sending the signal 15 to group 32624
[2024-04-04T11:26:15.455+0300] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-04T11:26:15.511+0300] {process_utils.py:79} INFO - Process psutil.Process(pid=32624, status='terminated', exitcode=0, started='11:26:05') (32624) terminated with exit code 0
