[2024-04-02T13:50:34.348+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-04-02T10:45:54.610177+00:00 [queued]>
[2024-04-02T13:50:34.360+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-04-02T10:45:54.610177+00:00 [queued]>
[2024-04-02T13:50:34.361+0300] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2024-04-02T13:50:34.375+0300] {taskinstance.py:2214} INFO - Executing <Task(ExternalTaskSensor): process_result.sensor_triggered_dag> on 2024-04-02 10:45:54.610177+00:00
[2024-04-02T13:50:34.379+0300] {standard_task_runner.py:60} INFO - Started process 19495 to run task
[2024-04-02T13:50:34.386+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'process_result.sensor_triggered_dag', 'manual__2024-04-02T10:45:54.610177+00:00', '--job-id', '1266', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmpyqbcgge9']
[2024-04-02T13:50:34.389+0300] {standard_task_runner.py:88} INFO - Job 1266: Subtask process_result.sensor_triggered_dag
[2024-04-02T13:50:34.561+0300] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-04-02T10:45:54.610177+00:00 [running]> on host C9843
[2024-04-02T13:50:34.748+0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='process_result.sensor_triggered_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T10:45:54.610177+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-02T10:45:54.610177+00:00'
[2024-04-02T13:50:34.751+0300] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-04-02T10:40:54.610177+00:00 ... 
[2024-04-02T13:50:44.595+0300] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-04-02T13:50:44.616+0300] {process_utils.py:131} INFO - Sending 15 to group 19495. PIDs of all processes in the group: [19495]
[2024-04-02T13:50:44.617+0300] {process_utils.py:86} INFO - Sending the signal 15 to group 19495
[2024-04-02T13:50:44.617+0300] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-02T13:50:44.679+0300] {process_utils.py:79} INFO - Process psutil.Process(pid=19495, status='terminated', exitcode=0, started='13:50:34') (19495) terminated with exit code 0
