[2024-03-27T14:52:02.816+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-27T12:49:32.688807+00:00 [queued]>
[2024-03-27T14:52:02.830+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-27T12:49:32.688807+00:00 [queued]>
[2024-03-27T14:52:02.830+0200] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2024-03-27T14:52:02.867+0200] {taskinstance.py:2214} INFO - Executing <Task(ExternalTaskSensor): process_result.sensor_triggered_dag> on 2024-03-27 12:49:32.688807+00:00
[2024-03-27T14:52:02.873+0200] {standard_task_runner.py:60} INFO - Started process 24790 to run task
[2024-03-27T14:52:02.882+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'process_result.sensor_triggered_dag', 'manual__2024-03-27T12:49:32.688807+00:00', '--job-id', '642', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp7gnbz504']
[2024-03-27T14:52:02.885+0200] {standard_task_runner.py:88} INFO - Job 642: Subtask process_result.sensor_triggered_dag
[2024-03-27T14:52:03.045+0200] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-27T12:49:32.688807+00:00 [running]> on host C9843
[2024-03-27T14:52:03.281+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='process_result.sensor_triggered_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T12:49:32.688807+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-27T12:49:32.688807+00:00'
[2024-03-27T14:52:03.283+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-27T12:44:32.688807+00:00 ... 
[2024-03-27T14:52:13.079+0200] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-03-27T14:52:13.102+0200] {process_utils.py:131} INFO - Sending 15 to group 24790. PIDs of all processes in the group: [24790]
[2024-03-27T14:52:13.103+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 24790
[2024-03-27T14:52:13.104+0200] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-27T14:52:13.159+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=24790, status='terminated', exitcode=0, started='14:52:02') (24790) terminated with exit code 0
