[2024-04-02T14:41:26.917+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-04-02T11:35:18.306981+00:00 [queued]>
[2024-04-02T14:41:26.926+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-04-02T11:35:18.306981+00:00 [queued]>
[2024-04-02T14:41:26.927+0300] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2024-04-02T14:41:26.954+0300] {taskinstance.py:2214} INFO - Executing <Task(ExternalTaskSensor): process_result.sensor_triggered_dag> on 2024-04-02 11:35:18.306981+00:00
[2024-04-02T14:41:26.959+0300] {standard_task_runner.py:60} INFO - Started process 39578 to run task
[2024-04-02T14:41:26.966+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'process_result.sensor_triggered_dag', 'manual__2024-04-02T11:35:18.306981+00:00', '--job-id', '1288', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp5l_p89p_']
[2024-04-02T14:41:26.969+0300] {standard_task_runner.py:88} INFO - Job 1288: Subtask process_result.sensor_triggered_dag
[2024-04-02T14:41:27.075+0300] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-04-02T11:35:18.306981+00:00 [running]> on host C9843
[2024-04-02T14:41:27.229+0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='process_result.sensor_triggered_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T11:35:18.306981+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-02T11:35:18.306981+00:00'
[2024-04-02T14:41:27.232+0300] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-04-02T11:35:18.306981+00:00 ... 
[2024-04-02T14:41:37.100+0300] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-04-02T14:41:37.115+0300] {process_utils.py:131} INFO - Sending 15 to group 39578. PIDs of all processes in the group: [39578]
[2024-04-02T14:41:37.115+0300] {process_utils.py:86} INFO - Sending the signal 15 to group 39578
[2024-04-02T14:41:37.116+0300] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-02T14:41:37.170+0300] {process_utils.py:79} INFO - Process psutil.Process(pid=39578, status='terminated', exitcode=0, started='14:41:26') (39578) terminated with exit code 0
