[2024-04-03T17:18:32.327+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.trigger_dag_task scheduled__2018-11-18T00:00:00+00:00 [queued]>
[2024-04-03T17:18:32.354+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.trigger_dag_task scheduled__2018-11-18T00:00:00+00:00 [queued]>
[2024-04-03T17:18:32.354+0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-03T17:18:32.366+0300] {taskinstance.py:2214} INFO - Executing <Task(TriggerDagRunOperator): trigger_dag_task> on 2018-11-18 00:00:00+00:00
[2024-04-03T17:18:32.370+0300] {standard_task_runner.py:60} INFO - Started process 34212 to run task
[2024-04-03T17:18:32.377+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'trigger_dag_task', 'scheduled__2018-11-18T00:00:00+00:00', '--job-id', '1476', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp6p8ogjby']
[2024-04-03T17:18:32.380+0300] {standard_task_runner.py:88} INFO - Job 1476: Subtask trigger_dag_task
[2024-04-03T17:18:32.478+0300] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.trigger_dag_task scheduled__2018-11-18T00:00:00+00:00 [running]> on host C9843
[2024-04-03T17:18:32.618+0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='trigger_dag_task' AIRFLOW_CTX_EXECUTION_DATE='2018-11-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2018-11-18T00:00:00+00:00'
[2024-04-03T17:18:32.772+0300] {trigger_dagrun.py:210} INFO - Waiting for dag_id_3 on 2024-04-03 14:18:32.620768+00:00 to become allowed state ['success'] ...
[2024-04-03T17:19:32.783+0300] {trigger_dagrun.py:210} INFO - Waiting for dag_id_3 on 2024-04-03 14:18:32.620768+00:00 to become allowed state ['success'] ...
[2024-04-03T17:20:32.807+0300] {trigger_dagrun.py:210} INFO - Waiting for dag_id_3 on 2024-04-03 14:18:32.620768+00:00 to become allowed state ['success'] ...
[2024-04-03T17:21:32.817+0300] {trigger_dagrun.py:210} INFO - Waiting for dag_id_3 on 2024-04-03 14:18:32.620768+00:00 to become allowed state ['success'] ...
[2024-04-03T17:22:32.856+0300] {trigger_dagrun.py:210} INFO - Waiting for dag_id_3 on 2024-04-03 14:18:32.620768+00:00 to become allowed state ['success'] ...
[2024-04-03T17:22:44.923+0300] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2024-04-03T17:22:44.941+0300] {process_utils.py:131} INFO - Sending 15 to group 34212. PIDs of all processes in the group: [34212]
[2024-04-03T17:22:44.941+0300] {process_utils.py:86} INFO - Sending the signal 15 to group 34212
[2024-04-03T17:22:44.942+0300] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-03T17:22:44.961+0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/operators/trigger_dagrun.py", line 216, in execute
    time.sleep(self.poke_interval)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2482, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-04-03T17:22:44.966+0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=trigger_dag, task_id=trigger_dag_task, execution_date=20181118T000000, start_date=20240403T141832, end_date=20240403T142244
[2024-04-03T17:22:44.981+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1476 for task trigger_dag_task (Task received SIGTERM signal; 34212)
[2024-04-03T17:22:44.996+0300] {process_utils.py:79} INFO - Process psutil.Process(pid=34212, status='terminated', exitcode=1, started='17:18:32') (34212) terminated with exit code 1
