[2024-03-27T12:47:50.693+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-26T13:30:30.034012+00:00 [queued]>
[2024-03-27T12:47:50.701+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-26T13:30:30.034012+00:00 [queued]>
[2024-03-27T12:47:50.702+0200] {taskinstance.py:2193} INFO - Starting attempt 2 of 1
[2024-03-27T12:47:50.715+0200] {taskinstance.py:2214} INFO - Executing <Task(ExternalTaskSensor): process_result.sensor_triggered_dag> on 2024-03-26 13:30:30.034012+00:00
[2024-03-27T12:47:50.719+0200] {standard_task_runner.py:60} INFO - Started process 5173 to run task
[2024-03-27T12:47:50.726+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'process_result.sensor_triggered_dag', 'manual__2024-03-26T13:30:30.034012+00:00', '--job-id', '608', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmpf3x5hmwk']
[2024-03-27T12:47:50.729+0200] {standard_task_runner.py:88} INFO - Job 608: Subtask process_result.sensor_triggered_dag
[2024-03-27T12:47:50.795+0200] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-26T13:30:30.034012+00:00 [running]> on host C9843
[2024-03-27T12:47:50.898+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='process_result.sensor_triggered_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-03-26T13:30:30.034012+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-26T13:30:30.034012+00:00'
[2024-03-27T12:47:50.900+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-26T13:25:30.034012+00:00 ... 
[2024-03-27T12:48:50.914+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-26T13:25:30.034012+00:00 ... 
[2024-03-27T12:49:50.924+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-26T13:25:30.034012+00:00 ... 
[2024-03-27T12:50:32.248+0200] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to queued. Terminating instance.
[2024-03-27T12:50:32.267+0200] {process_utils.py:131} INFO - Sending 15 to group 5173. PIDs of all processes in the group: [5173]
[2024-03-27T12:50:32.267+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 5173
[2024-03-27T12:50:32.267+0200] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-27T12:50:32.288+0200] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/base.py", line 293, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2482, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-27T12:50:32.294+0200] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=trigger_dag, task_id=process_result.sensor_triggered_dag, execution_date=20240326T133030, start_date=20240327T104750, end_date=20240327T105032
[2024-03-27T12:50:32.330+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 608 for task process_result.sensor_triggered_dag (Task received SIGTERM signal; 5173)
[2024-03-27T12:50:32.365+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=5173, status='terminated', exitcode=1, started='12:47:50') (5173) terminated with exit code 1
