[2024-03-27T15:08:12.189+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-27T13:07:55.338890+00:00 [queued]>
[2024-03-27T15:08:12.219+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-27T13:07:55.338890+00:00 [queued]>
[2024-03-27T15:08:12.220+0200] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-27T15:08:12.241+0200] {taskinstance.py:2214} INFO - Executing <Task(ExternalTaskSensor): process_result.sensor_triggered_dag> on 2024-03-27 13:07:55.338890+00:00
[2024-03-27T15:08:12.247+0200] {standard_task_runner.py:60} INFO - Started process 35138 to run task
[2024-03-27T15:08:12.256+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'process_result.sensor_triggered_dag', 'manual__2024-03-27T13:07:55.338890+00:00', '--job-id', '657', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmpq3d4oxp5']
[2024-03-27T15:08:12.260+0200] {standard_task_runner.py:88} INFO - Job 657: Subtask process_result.sensor_triggered_dag
[2024-03-27T15:08:12.389+0200] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-27T13:07:55.338890+00:00 [running]> on host C9843
[2024-03-27T15:08:12.591+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='process_result.sensor_triggered_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-03-27T13:07:55.338890+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-27T13:07:55.338890+00:00'
[2024-03-27T15:08:12.594+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-27T13:07:55.338890+00:00 ... 
[2024-03-27T15:09:12.624+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-27T13:07:55.338890+00:00 ... 
[2024-03-27T15:10:12.641+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-27T13:07:55.338890+00:00 ... 
[2024-03-27T15:11:12.669+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-27T13:07:55.338890+00:00 ... 
[2024-03-27T15:12:05.818+0200] {local_task_job_runner.py:280} WARNING - Recorded pid 37252 does not match the current pid 35138
[2024-03-27T15:12:05.846+0200] {process_utils.py:131} INFO - Sending 15 to group 35138. PIDs of all processes in the group: [35138]
[2024-03-27T15:12:05.846+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 35138
[2024-03-27T15:12:05.847+0200] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-27T15:12:05.879+0200] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/base.py", line 293, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2482, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-27T15:12:05.889+0200] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=trigger_dag, task_id=process_result.sensor_triggered_dag, execution_date=20240327T130755, start_date=20240327T131202, end_date=20240327T131205
[2024-03-27T15:12:05.927+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 657 for task process_result.sensor_triggered_dag (Task received SIGTERM signal; 35138)
[2024-03-27T15:12:05.940+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=35138, status='terminated', exitcode=1, started='15:08:12') (35138) terminated with exit code 1
