[2024-04-02T13:53:47.359+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-04-02T10:51:30.966512+00:00 [queued]>
[2024-04-02T13:53:47.373+0300] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-04-02T10:51:30.966512+00:00 [queued]>
[2024-04-02T13:53:47.373+0300] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-02T13:53:47.399+0300] {taskinstance.py:2214} INFO - Executing <Task(ExternalTaskSensor): process_result.sensor_triggered_dag> on 2024-04-02 10:51:30.966512+00:00
[2024-04-02T13:53:47.404+0300] {standard_task_runner.py:60} INFO - Started process 20809 to run task
[2024-04-02T13:53:47.411+0300] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'process_result.sensor_triggered_dag', 'manual__2024-04-02T10:51:30.966512+00:00', '--job-id', '1274', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp8695d9vb']
[2024-04-02T13:53:47.415+0300] {standard_task_runner.py:88} INFO - Job 1274: Subtask process_result.sensor_triggered_dag
[2024-04-02T13:53:47.522+0300] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-04-02T10:51:30.966512+00:00 [running]> on host C9843
[2024-04-02T13:53:47.673+0300] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='process_result.sensor_triggered_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T10:51:30.966512+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-02T10:51:30.966512+00:00'
[2024-04-02T13:53:47.675+0300] {external_task.py:244} INFO - Poking for tasks ['create_table_task'] in dag dag_id_3 on 2024-04-02T10:46:30.966512+00:00 ... 
[2024-04-02T13:54:47.707+0300] {external_task.py:244} INFO - Poking for tasks ['create_table_task'] in dag dag_id_3 on 2024-04-02T10:46:30.966512+00:00 ... 
[2024-04-02T13:55:38.659+0300] {local_task_job_runner.py:280} WARNING - Recorded pid 21568 does not match the current pid 20809
[2024-04-02T13:55:38.676+0300] {process_utils.py:131} INFO - Sending 15 to group 20809. PIDs of all processes in the group: [20809]
[2024-04-02T13:55:38.676+0300] {process_utils.py:86} INFO - Sending the signal 15 to group 20809
[2024-04-02T13:55:38.677+0300] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-04-02T13:55:38.699+0300] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/base.py", line 293, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2482, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-04-02T13:55:38.706+0300] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=trigger_dag, task_id=process_result.sensor_triggered_dag, execution_date=20240402T105130, start_date=20240402T105534, end_date=20240402T105538
[2024-04-02T13:55:38.740+0300] {standard_task_runner.py:107} ERROR - Failed to execute job 1274 for task process_result.sensor_triggered_dag (Task received SIGTERM signal; 20809)
[2024-04-02T13:55:38.770+0300] {process_utils.py:79} INFO - Process psutil.Process(pid=20809, status='terminated', exitcode=1, started='13:53:47') (20809) terminated with exit code 1
