[2024-03-29T11:18:16.643+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-29T09:16:57.558161+00:00 [queued]>
[2024-03-29T11:18:16.652+0200] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-29T09:16:57.558161+00:00 [queued]>
[2024-03-29T11:18:16.652+0200] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-03-29T11:18:16.687+0200] {taskinstance.py:2214} INFO - Executing <Task(ExternalTaskSensor): process_result.sensor_triggered_dag> on 2024-03-29 09:16:57.558161+00:00
[2024-03-29T11:18:16.691+0200] {standard_task_runner.py:60} INFO - Started process 29253 to run task
[2024-03-29T11:18:16.699+0200] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'trigger_dag', 'process_result.sensor_triggered_dag', 'manual__2024-03-29T09:16:57.558161+00:00', '--job-id', '1199', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/var/folders/t6/vwjsg0jx26jcjdwn_gxhbjzc0000gp/T/tmp2edldr82']
[2024-03-29T11:18:16.703+0200] {standard_task_runner.py:88} INFO - Job 1199: Subtask process_result.sensor_triggered_dag
[2024-03-29T11:18:16.844+0200] {task_command.py:423} INFO - Running <TaskInstance: trigger_dag.process_result.sensor_triggered_dag manual__2024-03-29T09:16:57.558161+00:00 [running]> on host C9843
[2024-03-29T11:18:17.047+0200] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='trigger_dag' AIRFLOW_CTX_TASK_ID='process_result.sensor_triggered_dag' AIRFLOW_CTX_EXECUTION_DATE='2024-03-29T09:16:57.558161+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-29T09:16:57.558161+00:00'
[2024-03-29T11:18:17.050+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-29T09:11:57.558161+00:00 ... 
[2024-03-29T11:19:17.085+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-29T09:11:57.558161+00:00 ... 
[2024-03-29T11:20:17.097+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-29T09:11:57.558161+00:00 ... 
[2024-03-29T11:21:17.108+0200] {external_task.py:260} INFO - Poking for DAG 'dag_id_3' on 2024-03-29T09:11:57.558161+00:00 ... 
[2024-03-29T11:21:28.949+0200] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to None. Terminating instance.
[2024-03-29T11:21:28.969+0200] {process_utils.py:131} INFO - Sending 15 to group 29253. PIDs of all processes in the group: [29253]
[2024-03-29T11:21:28.970+0200] {process_utils.py:86} INFO - Sending the signal 15 to group 29253
[2024-03-29T11:21:28.970+0200] {taskinstance.py:2480} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-03-29T11:21:28.997+0200] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/external_task.py", line 334, in execute
    super().execute(context)
  File "/usr/local/lib/python3.8/site-packages/airflow/sensors/base.py", line 293, in execute
    time.sleep(self._get_next_poke_interval(started_at, run_duration, try_number))
  File "/usr/local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2482, in signal_handler
    raise AirflowException("Task received SIGTERM signal")
airflow.exceptions.AirflowException: Task received SIGTERM signal
[2024-03-29T11:21:29.003+0200] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=trigger_dag, task_id=process_result.sensor_triggered_dag, execution_date=20240329T091657, start_date=20240329T091816, end_date=20240329T092129
[2024-03-29T11:21:29.038+0200] {standard_task_runner.py:107} ERROR - Failed to execute job 1199 for task process_result.sensor_triggered_dag (Task received SIGTERM signal; 29253)
[2024-03-29T11:21:29.067+0200] {process_utils.py:79} INFO - Process psutil.Process(pid=29253, status='terminated', exitcode=1, started='11:18:16') (29253) terminated with exit code 1
